server:
  port: 8080
  application:
    name: rest-api

spring:
  webflux:
    base-path: /demo

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: debug